### PR TITLE
Use `pronamic/pronamic-changelog-md-to-wordpress-plugin-readme-txt`

### PR DESCRIPTION
**Pull request by remcotolsma**

### CODE REVIEW

**Comment by remcotolsma** [comment]
I have tested this on https://plugins.trac.wordpress.org/browser/salesfeed/tags/1.3.3/readme.txt, but it is not reflected on https://nl.wordpress.org/plugins/salesfeed/#developers. It seems there are some issues on WordPress.org.

> Is anyone aware of this issue? I just committed the first version of a plugin, and got this even though readme.txt has a Stable tag: 1.0.0 header, and the latest commit does have tags/1.0.0 it also looks like someone else has a similar issue an hour ago: https://wordpress.org/support/topic/stable-tag-issue/ 

https://wordpress.slack.com/archives/C1LBM36LC/p1727782407080529

> There's a possible ongoing DDoS right now which is impacting things unfortunately, I'd suggest trying again in like 5-10 minutes :slightly_smiling_face:

https://wordpress.slack.com/archives/C02RQBWTW/p1727772874487819

If this is working on ok and approved by @rvdsteege we can tag 1.0.0 of https://github.com/pronamic/pronamic-changelog-md-to-wordpress-plugin-readme-txt.

**Comment by rvdsteege** [comment]
Nice! 🚀

Do I understand correctly though, that the start and end markers in the `CHANGELOG.md` file need to be updated manually for each release? Would it be possible / nice if that is optional and that, by default (without any markers in the Markdown), it just takes the same number of releases that are already between the markers in the `readme.txt` (number of lines starting with `## `) and replace these with the releases from the Markdown?

**Review by rvdsteege — COMMENTED** [review]
Nice! 🚀

Do I understand correctly though, that the start and end markers in the `CHANGELOG.md` file need to be updated manually for each release? Would it be possible / nice if that is optional and that, by default (without any markers in the Markdown), it just takes the same number of releases that are already between the markers in the `readme.txt` (number of lines starting with `## `) and replace these with the releases from the Markdown?

**Comment by remcotolsma** [comment]
> Do I understand correctly though, that the start and end markers in the `CHANGELOG.md` file need to be updated manually for each release?

Yes, that's right.

> Would it be possible / nice if that is optional and that, by default (without any markers in the Markdown), it just takes the same number of releases that are already between the markers in the `readme.txt` (number of lines starting with `## `) and replace these with the releases from the Markdown?

Yes, that could be done, but it would make the https://github.com/pronamic/pronamic-changelog-md-to-wordpress-plugin-readme-txt library a bit more complex. That's why I mentioned this in the `README.md`:

> ## Usage
> 
> To keep this library simple, two markers are needed in `CHANGELOG.md` and `readme.txt`.
> 
> ```
> 
> ```
> 
> ```
> 
> ```

https://github.com/pronamic/pronamic-changelog-md-to-wordpress-plugin-readme-txt?tab=readme-ov-file#usage

It may not be a big deal that changelog entries in the `readme.txt` file grow. In that respect, the `<!-- End changelog -->` does not need to be moved up for every release. After a certain number of major releases, it may be decided to move the marker up a bit. This way users have full control over this and we can keep the https://github.com/pronamic/pronamic-changelog-md-to-wordpress-plugin-readme-txt library simple for now?

**Review by rvdsteege — APPROVED** [review]
We'll experience if this works in practice 🙂 If `pronamic/pronamic-changelog-md-to-wordpress-plugin-readme-txt` needs any improvements later, I'll open an issue there.

**Pull request merged**
